### ISSUE TITLE
npm workspace로 루트 package 만들기

### ISSUE THREAD

**Issue by sjuuun** [hyunW3/react_practice#16]
## 제안

- npm workspace로 client와 server의 공통 dependency를 한번에 정의하면 좋겠어요.

참고 - [npm workspace](https://docs.npmjs.com/cli/v7/using-npm/workspaces)

_Originally posted by @sjuuun in https://github.com/hyunW3/BlogReact/pull/15#discussion_r720753156_

**Comment by hyunW3** [comment]
## 추가사항 
PR #19 에서 eslint와 prettier 설정파일을 클라와 서버에서 정의하지 않고,
루트에서 같이 정의하는 것을 해보기로 했어요.

**Comment by hyunW3** [comment]
workspace를 사용하지만(하나의 node_modules 폴더 사용), 현재 prettier, linter json 파일도 client/server 각각 따로 존재합니다. 이 부분도 통일하자는 의견이 나왔어요.
