### ISSUE TITLE
테스트용 콘솔 로그 지우기

### ISSUE THREAD

**Issue by sjuuun** [hyunW3/react_practice#5]
## 수정할 사항

- 테스트용으로 작성한 콘솔 로그를 지우면 좋겠어요.

## 왜 필요한가요?

- 테스트용이라 코드 알아보기에 불편해요!

**Comment by hyunW3** [comment]
서버쪽 콘솔로그를 지우지 못하였네요.

**Comment by sjuuun** [comment]
- [ ] 클라이언트 콘솔로그 삭제
- [ ] 서버 콘솔로그 삭제

**Comment by hyunW3** [comment]
> * [x]  클라이언트 콘솔로그 삭제
> * [x]  서버 콘솔로그 삭제
